secrity: fix warning security/apparmor/domain.c:110:17: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]         } else if ((ns == profile->ns)) {                     ~~~^~~~~~~~~~~~~~ ../security/apparmor/domain.c:110:17: note: remove extraneous parentheses around the comparison to silence this warning         } else if ((ns == profile->ns)) {                    ~   ^             ~ ../security/apparmor/domain.c:110:17: note: use '=' to turn this equality comparison into an assignment         } else if ((ns == profile->ns)) {                        ^~                        = 1 error generated.
apparmor: use SHASH_DESC_ON_STACK

When building the kernel with clang, the compiler fails to build
security/apparmor/crypto.c with the following error:

    security/apparmor/crypto.c:36:8: error: fields must have a constant
    size: 'variable length array in structure' extension will never be
    supported
                    char ctx[crypto_shash_descsize(apparmor_tfm)];
                         ^
Since commit a0a77af ("crypto: LLVMLinux: Add macro to remove use
of VLAIS in crypto code"), include/crypto/hash.h defines
SHASH_DESC_ON_STACK to work around this issue. Use it in aa_calc_hash()
and aa_calc_profile_hash().

security/apparmor/crypto.c:37:8: error: fields must have a constant
size: 'variable length array in structure' extension will never be
supported
                char ctx[crypto_shash_descsize(apparmor_tfm)];
                     ^

Change-Id: I7668f8c6440660e7b68afd8aefd066e496f3beb4
Signed-off-by: Nicolas Iooss <nicolas.iooss_linux@m4x.org>
Signed-off-by: John Johansen <john.johansen@canonical.com>
Signed-off-by: James Morris <james.l.morris@oracle.com>
Git-commit: 9814448da7a84dd50b69e4ada2d7d1c042493daf
Git-repo:
git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
Signed-off-by: Shiraz Hashim <shashim@codeaurora.org>
1 error generated.